'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import { 
  Search, 
  Filter,
  Eye,
  CheckCircle,
  XCircle,
  Clock,
  Download,
  FileText,
  User,
  GraduationCap,
  ChevronLeft,
  ChevronRight
} from 'lucide-react';
import { toast } from 'sonner';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { mockApplications, mockUsers, mockScholarships, mockUserProfiles } from '@/lib/mock-data';
import { ConfirmModal } from '@/components/ui/confirm-modal';
import { RejectModal } from '@/components/ui/reject-modal';
import { ViewApplicationModal } from '@/components/ui/view-application-modal';

export default function ApplicationsManagement() {
  const router = useRouter();
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedStatus, setSelectedStatus] = useState('all');
  const [currentPage, setCurrentPage] = useState(1);
  const [viewModal, setViewModal] = useState<{ isOpen: boolean; application: any | null }>({
    isOpen: false,
    application: null
  });
  const [approveModal, setApproveModal] = useState<{ isOpen: boolean; appId: string; studentName: string; scholarship: string }>({
    isOpen: false,
    appId: '',
    studentName: '',
    scholarship: ''
  });
  const [rejectModal, setRejectModal] = useState<{ isOpen: boolean; appId: string; studentName: string; scholarship: string }>({
    isOpen: false,
    appId: '',
    studentName: '',
    scholarship: ''
  });
  const itemsPerPage = 10;

  // Handlers
  const handleExportReport = () => {
    const date = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });

    const reportContent = `
EduMatch Applications Report
Generated: ${date}

===========================================
APPLICATIONS SUMMARY
===========================================

Total Applications: ${applications.length}
- Pending: ${stats.pending}
- Under Review: ${stats.underReview}
- Approved: ${stats.approved}
- Rejected: ${stats.rejected}

===========================================
DETAILED APPLICATIONS
===========================================

${applications.map((app, i) => `
${i + 1}. ${app.id}
   Student: ${app.studentName} (${app.studentEmail})
   Scholarship: ${app.scholarship}
   Provider: ${app.provider}
   Amount: ${app.amount}
   GPA: ${app.gpa}
   Status: ${app.status}
   Submitted: ${app.submittedDate}
   Documents: ${app.documents}
`).join('\n')}

===========================================
Generated by EduMatch Admin System
===========================================
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `applications-report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);

    toast.success('Report Exported', {
      description: 'Applications report has been downloaded successfully',
    });
  };

  const handleViewApplication = (appId: string) => {
    // Find the application data
    const app = applications.find(a => a.id === appId);
    if (app) {
      setViewModal({ isOpen: true, application: app });
    }
  };

  const handleApproveApplication = (appId: string, studentName: string, scholarship: string) => {
    setApproveModal({ isOpen: true, appId, studentName, scholarship });
  };

  const confirmApproveApplication = () => {
    toast.success('Application Approved', {
      description: `${approveModal.studentName}'s application has been approved. Student and provider notified.`,
    });
    console.log('Approving application:', approveModal.appId);
    setApproveModal({ isOpen: false, appId: '', studentName: '', scholarship: '' });
  };

  const handleRejectApplication = (appId: string, studentName: string, scholarship: string) => {
    setRejectModal({ isOpen: true, appId, studentName, scholarship });
  };

  const confirmRejectApplication = (reason: string) => {
    toast.error('Application Rejected', {
      description: `${rejectModal.studentName}'s application has been rejected. Student notified.`,
    });
    console.log('Rejecting application:', rejectModal.appId, 'Reason:', reason);
    setRejectModal({ isOpen: false, appId: '', studentName: '', scholarship: '' });
  };

  // Use real mock applications
  const applications = mockApplications.map(app => {
    const student = mockUsers.find(u => u.id === app.applicantId);
    const scholarship = mockScholarships.find(s => s.id === app.scholarshipId);
    const profile = mockUserProfiles.find(p => p.id === app.applicantId);
    
    return {
      id: app.id.toUpperCase(),
      studentName: student?.name || 'Unknown',
      studentEmail: student?.email || 'unknown@example.com',
      scholarship: scholarship?.title || 'Unknown Scholarship',
      provider: scholarship?.providerName || scholarship?.university || 'Unknown',
      amount: `$${(scholarship?.amount || 0).toLocaleString()}`,
      status: app.status === 'ACCEPTED' ? 'Approved' : app.status === 'REJECTED' ? 'Rejected' : app.status === 'UNDER_REVIEW' ? 'Under Review' : 'Pending',
      submittedDate: app.submittedAt ? new Date(app.submittedAt).toISOString().split('T')[0] : '2024-03-15',
      gpa: profile?.gpa || 3.5,
      documents: app.additionalDocs?.length || 0
    };
  });

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'Approved':
        return 'bg-green-100 text-green-700';
      case 'Pending':
        return 'bg-yellow-100 text-yellow-700';
      case 'Under Review':
        return 'bg-blue-100 text-blue-700';
      case 'Rejected':
        return 'bg-red-100 text-red-700';
      default:
        return 'bg-gray-100 text-gray-700';
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'Approved':
        return <CheckCircle className="w-4 h-4" />;
      case 'Pending':
        return <Clock className="w-4 h-4" />;
      case 'Under Review':
        return <Eye className="w-4 h-4" />;
      case 'Rejected':
        return <XCircle className="w-4 h-4" />;
      default:
        return null;
    }
  };

  const filteredApplications = applications.filter(app => {
    const matchesSearch = 
      app.studentName.toLowerCase().includes(searchQuery.toLowerCase()) ||
      app.scholarship.toLowerCase().includes(searchQuery.toLowerCase()) ||
      app.id.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesStatus = selectedStatus === 'all' || app.status === selectedStatus;
    
    return matchesSearch && matchesStatus;
  });

  const totalPages = Math.ceil(filteredApplications.length / itemsPerPage);
  const startIndex = (currentPage - 1) * itemsPerPage;
  const paginatedApplications = filteredApplications.slice(startIndex, startIndex + itemsPerPage);

  const stats = {
    total: applications.length,
    pending: applications.filter(a => a.status === 'Pending').length,
    underReview: applications.filter(a => a.status === 'Under Review').length,
    approved: applications.filter(a => a.status === 'Approved').length,
    rejected: applications.filter(a => a.status === 'Rejected').length
  };

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Application Management</h1>
          <p className="text-gray-500 mt-1">Review and manage scholarship applications</p>
        </div>
        <Button 
          onClick={handleExportReport}
          className="bg-blue-600 hover:bg-blue-700"
        >
          <Download className="w-4 h-4 mr-2" />
          Export Report
        </Button>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
        <Card className="card-minimal">
          <CardContent className="p-4">
            <p className="text-sm text-gray-500">Total Applications</p>
            <h3 className="text-2xl font-bold text-gray-900 mt-1">{stats.total}</h3>
          </CardContent>
        </Card>
        <Card className="card-minimal">
          <CardContent className="p-4">
            <p className="text-sm text-gray-500">Pending</p>
            <h3 className="text-2xl font-bold text-yellow-600 mt-1">{stats.pending}</h3>
          </CardContent>
        </Card>
        <Card className="card-minimal">
          <CardContent className="p-4">
            <p className="text-sm text-gray-500">Under Review</p>
            <h3 className="text-2xl font-bold text-blue-600 mt-1">{stats.underReview}</h3>
          </CardContent>
        </Card>
        <Card className="card-minimal">
          <CardContent className="p-4">
            <p className="text-sm text-gray-500">Approved</p>
            <h3 className="text-2xl font-bold text-green-600 mt-1">{stats.approved}</h3>
          </CardContent>
        </Card>
        <Card className="card-minimal">
          <CardContent className="p-4">
            <p className="text-sm text-gray-500">Rejected</p>
            <h3 className="text-2xl font-bold text-red-600 mt-1">{stats.rejected}</h3>
          </CardContent>
        </Card>
      </div>

      {/* Filters and Search */}
      <Card className="card-minimal">
        <CardContent className="p-6">
          <div className="flex flex-col lg:flex-row gap-4">
            {/* Search */}
            <div className="flex-1 relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
              <input
                type="text"
                placeholder="Search by student name, scholarship, or application ID..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>

            {/* Status Filter */}
            <select
              value={selectedStatus}
              onChange={(e) => setSelectedStatus(e.target.value)}
              className="px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value="all">All Status</option>
              <option value="Pending">Pending</option>
              <option value="Under Review">Under Review</option>
              <option value="Approved">Approved</option>
              <option value="Rejected">Rejected</option>
            </select>
          </div>
        </CardContent>
      </Card>

      {/* Applications Table */}
      <Card className="card-minimal">
        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-50 border-b border-gray-200">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Application ID
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Student
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Scholarship
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Amount
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    GPA
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Status
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Submitted
                  </th>
                  <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {paginatedApplications.map((app) => (
                  <tr key={app.id} className="hover:bg-gray-50 transition-colors">
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center">
                        <FileText className="w-4 h-4 text-gray-400 mr-2" />
                        <span className="font-mono text-sm font-semibold text-gray-900">
                          {app.id}
                        </span>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center">
                        <div className="w-8 h-8 rounded-full bg-blue-600 flex items-center justify-center text-white text-xs font-semibold">
                          {app.studentName.split(' ').map(n => n[0]).join('')}
                        </div>
                        <div className="ml-3">
                          <div className="font-semibold text-gray-900">{app.studentName}</div>
                          <div className="text-xs text-gray-500">{app.studentEmail}</div>
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      <div>
                        <div className="font-semibold text-gray-900">{app.scholarship}</div>
                        <div className="text-sm text-gray-500">{app.provider}</div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="font-semibold text-gray-900">{app.amount}</span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="font-semibold text-gray-900">{app.gpa}</span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <Badge className={`${getStatusColor(app.status)} flex items-center gap-1 w-fit`}>
                        {getStatusIcon(app.status)}
                        {app.status}
                      </Badge>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {new Date(app.submittedDate).toLocaleDateString()}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-right">
                      <div className="flex items-center justify-end gap-2">
                        <Button 
                          variant="outline" 
                          size="sm"
                          onClick={() => handleViewApplication(app.id)}
                          title="View details"
                        >
                          <Eye className="w-4 h-4" />
                        </Button>
                        {app.status === 'Pending' || app.status === 'Under Review' ? (
                          <>
                            <Button 
                              variant="outline" 
                              size="sm" 
                              className="text-green-600 hover:text-green-700"
                              onClick={() => handleApproveApplication(app.id, app.studentName, app.scholarship)}
                              title="Approve application"
                            >
                              <CheckCircle className="w-4 h-4" />
                            </Button>
                            <Button 
                              variant="outline" 
                              size="sm" 
                              className="text-red-600 hover:text-red-700"
                              onClick={() => handleRejectApplication(app.id, app.studentName, app.scholarship)}
                              title="Reject application"
                            >
                              <XCircle className="w-4 h-4" />
                            </Button>
                          </>
                        ) : null}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Pagination */}
          <div className="px-6 py-4 border-t border-gray-200 flex items-center justify-between">
            <p className="text-sm text-gray-500">
              Showing {startIndex + 1} to {Math.min(startIndex + itemsPerPage, filteredApplications.length)} of {filteredApplications.length} applications
            </p>
            <div className="flex items-center gap-2">
              <Button
                variant="outline"
                size="sm"
                onClick={() => setCurrentPage(prev => Math.max(1, prev - 1))}
                disabled={currentPage === 1}
              >
                <ChevronLeft className="w-4 h-4" />
              </Button>
              <span className="text-sm text-gray-700">
                Page {currentPage} of {totalPages}
              </span>
              <Button
                variant="outline"
                size="sm"
                onClick={() => setCurrentPage(prev => Math.min(totalPages, prev + 1))}
                disabled={currentPage === totalPages}
              >
                <ChevronRight className="w-4 h-4" />
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Approve Confirmation Modal */}
      <ConfirmModal
        isOpen={approveModal.isOpen}
        onClose={() => setApproveModal({ isOpen: false, appId: '', studentName: '', scholarship: '' })}
        onConfirm={confirmApproveApplication}
        title="Approve Application"
        description={`Approve ${approveModal.studentName}'s application for ${approveModal.scholarship}? Student and provider will be notified.`}
        variant="success"
        confirmText="Approve Application"
      />

      {/* Reject Modal */}
      <RejectModal
        isOpen={rejectModal.isOpen}
        onClose={() => setRejectModal({ isOpen: false, appId: '', studentName: '', scholarship: '' })}
        onSubmit={confirmRejectApplication}
        title={`Reject ${rejectModal.studentName}'s Application`}
        placeholder="Explain why this application is being rejected (minimum 10 characters)..."
      />

      {/* View Application Detail Modal */}
      <ViewApplicationModal
        isOpen={viewModal.isOpen}
        onClose={() => setViewModal({ isOpen: false, application: null })}
        application={viewModal.application}
      />
    </div>
  );
}
