'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { 
  Users, 
  GraduationCap, 
  FileText, 
  TrendingUp,
  ArrowUpRight,
  ArrowDownRight,
  Calendar,
  DollarSign
} from 'lucide-react';
import { toast } from 'sonner';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
// MOCK DATA REMOVED - TODO: Integrate with real backend API
import { UserRole } from '@/types';
import { formatDistanceToNow } from 'date-fns';
import { useLanguage } from '@/contexts/LanguageContext';
import Link from 'next/link';
import { pageVariants, statCardVariants, listContainerVariants, listItemVariants } from '@/lib/animations';

export default function AdminDashboard() {
  const { t } = useLanguage();
  // Calculate real stats from mock data
  const totalUsers = mockUsers.length;
  const activeScholarships = mockScholarships.filter(s => s.status === 'PUBLISHED').length;
  const pendingApplications = mockApplications.filter(a => a.status === 'SUBMITTED' || a.status === 'UNDER_REVIEW').length;
  const totalFunding = mockScholarships.reduce((sum, s) => sum + (s.amount || 0), 0);

  const handleGenerateReport = () => {
    // Get current date for report
    const date = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });

    // Create report data
    const reportData = {
      date,
      totalUsers,
      activeScholarships,
      pendingApplications,
      totalFunding,
      students: mockUsers.filter(u => u.role === UserRole.STUDENT).length,
      providers: mockUsers.filter(u => u.role === UserRole.PROVIDER).length,
      acceptedApplications: mockApplications.filter(a => a.status === 'ACCEPTED').length,
      rejectedApplications: mockApplications.filter(a => a.status === 'REJECTED').length,
    };

    // Create report content
    const reportContent = `
EduMatch Admin Report
Generated: ${reportData.date}

===========================================
SYSTEM OVERVIEW
===========================================

Users Statistics:
- Total Users: ${reportData.totalUsers}
- Students: ${reportData.students}
- Providers: ${reportData.providers}

Scholarships Statistics:
- Active Scholarships: ${reportData.activeScholarships}
- Total Funding Available: $${reportData.totalFunding.toLocaleString()}

Applications Statistics:
- Pending Applications: ${reportData.pendingApplications}
- Accepted Applications: ${reportData.acceptedApplications}
- Rejected Applications: ${reportData.rejectedApplications}
- Total Applications: ${mockApplications.length}

===========================================
DETAILED BREAKDOWN
===========================================

Recent Applications:
${mockApplications.slice(0, 5).map((app, i) => {
  const student = mockUsers.find(u => u.id === app.applicantId);
  const scholarship = mockScholarships.find(s => s.id === app.scholarshipId);
  return `${i + 1}. ${student?.name} - ${scholarship?.title} (${app.status})`;
}).join('\n')}

Recent Users:
${mockUsers.slice(0, 5).map((user, i) => {
  return `${i + 1}. ${user.name} - ${user.email} (${user.role})`;
}).join('\n')}

===========================================
Generated by EduMatch Admin System
===========================================
    `.trim();

    // Create and download report
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `edumatch-report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);

    // Show success message
    toast.success(t('admin.report.success'), {
      description: t('admin.report.successDescription'),
    });
  };

  const stats = [
    {
      title: t('admin.stats.totalUsers'),
      value: totalUsers.toString(),
      change: '+12.5%',
      trend: 'up',
      icon: Users,
      color: 'bg-blue-500',
      link: '/admin/users'
    },
    {
      title: t('admin.stats.activeScholarships'),
      value: activeScholarships.toString(),
      change: '+5.2%',
      trend: 'up',
      icon: GraduationCap,
      color: 'bg-green-500',
      link: '/admin/scholarships'
    },
    {
      title: t('admin.stats.pendingApplications'),
      value: pendingApplications.toString(),
      change: '-3.1%',
      trend: 'down',
      icon: FileText,
      color: 'bg-orange-500',
      link: '/admin/applications'
    },
    {
      title: t('admin.stats.totalFunding'),
      value: `$${(totalFunding / 1000).toFixed(1)}K`,
      change: '+18.2%',
      trend: 'up',
      icon: DollarSign,
      color: 'bg-purple-500',
      link: '/admin/scholarships'
    }
  ];

  // Get recent applications with real data
  const recentApplications = mockApplications
    .filter(app => app.submittedAt) // Only applications with submission date
    .sort((a, b) => new Date(b.submittedAt!).getTime() - new Date(a.submittedAt!).getTime())
    .slice(0, 4)
    .map(app => {
      const student = mockUsers.find(u => u.id === app.applicantId);
      const scholarship = mockScholarships.find(s => s.id === app.scholarshipId);
      
      return {
        id: app.id,
        studentName: student?.name || 'Unknown',
        scholarship: scholarship?.title || 'Unknown Scholarship',
        amount: `$${(scholarship?.amount || 0).toLocaleString()}`,
        status: app.status.toLowerCase().replace('_', ' '),
        date: formatDistanceToNow(new Date(app.submittedAt!), { addSuffix: true })
      };
    });

  // Get recent users with real data
  const recentUsers = mockUsers
    .filter(u => u.role !== UserRole.ADMIN) // Exclude admin from recent users
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    .slice(0, 3)
    .map(user => {
      const initials = (user.name || 'U')
        .split(' ')
        .map(n => n[0])
        .join('')
        .toUpperCase();
      
      return {
        id: user.id,
        name: user.name || 'Unknown',
        email: user.email,
        role: user.role === UserRole.STUDENT ? 'Student' : 'Provider',
        joinDate: formatDistanceToNow(new Date(user.createdAt), { addSuffix: true }),
        avatar: initials
      };
    });

  const getStatusColor = (status: string) => {
    if (status.includes('accepted')) return 'bg-green-100 text-green-700';
    if (status.includes('submitted') || status.includes('under review')) return 'bg-yellow-100 text-yellow-700';
    if (status.includes('rejected')) return 'bg-red-100 text-red-700';
    return 'bg-gray-100 text-gray-700';
  };

  return (
    <motion.div
      className="space-y-6"
      variants={pageVariants}
      initial="initial"
      animate="animate"
      exit="exit"
    >
      {/* Page Header */}
      <motion.div
        className="flex items-center justify-between"
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4 }}
      >
        <div>
          <h1 className="text-3xl font-bold text-gray-900">{t('admin.dashboard.title')}</h1>
          <p className="text-gray-500 mt-1">{t('admin.dashboard.subtitle')}</p>
        </div>
        <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
          <Button 
            onClick={handleGenerateReport}
            className="bg-blue-600 hover:bg-blue-700"
          >
            <Calendar className="w-4 h-4 mr-2" />
            {t('admin.dashboard.generateReport')}
          </Button>
        </motion.div>
      </motion.div>

      {/* Stats Grid */}
      <motion.div
        className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6"
        variants={listContainerVariants}
        initial="initial"
        animate="animate"
      >
        {stats.map((stat, index) => {
          const Icon = stat.icon;
          const TrendIcon = stat.trend === 'up' ? ArrowUpRight : ArrowDownRight;
          
          return (
            <motion.div key={index} variants={listItemVariants}>
              <motion.div variants={statCardVariants} whileHover="hover">
                <Card className="card-minimal">
                  <CardContent className="p-6">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex-1">
                    <p className="text-sm font-medium text-gray-500">{stat.title}</p>
                    <h3 className="text-3xl font-bold text-gray-900 mt-2">{stat.value}</h3>
                    <div className="flex items-center mt-2">
                      <TrendIcon 
                        className={`w-4 h-4 ${
                          stat.trend === 'up' ? 'text-green-600' : 'text-red-600'
                        }`} 
                      />
                      <span 
                        className={`text-sm font-medium ml-1 ${
                          stat.trend === 'up' ? 'text-green-600' : 'text-red-600'
                        }`}
                      >
                        {stat.change}
                      </span>
                      <span className="text-sm text-gray-500 ml-1">{t('admin.stats.vsLastMonth')}</span>
                    </div>
                  </div>
                  <div className={`${stat.color} w-12 h-12 rounded-lg flex items-center justify-center`}>
                    <Icon className="w-6 h-6 text-white" />
                  </div>
                </div>
                <Link href={stat.link}>
                  <Button variant="outline" size="sm" className="w-full">
                    {t('admin.stats.viewAll')}
                  </Button>
                </Link>
              </CardContent>
            </Card>
              </motion.div>
            </motion.div>
          );
        })}
      </motion.div>

      <motion.div
        className="grid grid-cols-1 lg:grid-cols-2 gap-6"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.4, duration: 0.5 }}
      >
        {/* Recent Applications */}
        <Card className="card-minimal">
          <CardHeader>
            <CardTitle className="text-lg font-semibold">{t('admin.recentApplications.title')}</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {recentApplications.map((application) => (
                <div 
                  key={application.id}
                  className="flex items-center justify-between p-4 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors"
                >
                  <div className="flex-1">
                    <h4 className="font-semibold text-gray-900">{application.studentName}</h4>
                    <p className="text-sm text-gray-600">{application.scholarship}</p>
                    <p className="text-xs text-gray-500 mt-1">{application.date}</p>
                  </div>
                  <div className="text-right">
                    <p className="font-semibold text-gray-900">{application.amount}</p>
                    <Badge className={`mt-1 ${getStatusColor(application.status)}`}>
                      {application.status}
                    </Badge>
                  </div>
                </div>
              ))}
            </div>
            <Button variant="outline" className="w-full mt-4">
              {t('admin.recentApplications.viewAll')}
            </Button>
          </CardContent>
        </Card>

        {/* Recent Users */}
        <Card className="card-minimal">
          <CardHeader>
            <CardTitle className="text-lg font-semibold">{t('admin.recentUsers.title')}</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {recentUsers.map((user) => (
                <div 
                  key={user.id}
                  className="flex items-center gap-4 p-4 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors"
                >
                  <div className="w-12 h-12 rounded-full bg-blue-600 flex items-center justify-center text-white font-semibold">
                    {user.avatar}
                  </div>
                  <div className="flex-1">
                    <h4 className="font-semibold text-gray-900">{user.name}</h4>
                    <p className="text-sm text-gray-600">{user.email}</p>
                    <p className="text-xs text-gray-500 mt-1">{user.joinDate}</p>
                  </div>
                  <Badge variant="secondary">{user.role}</Badge>
                </div>
              ))}
            </div>
            <Button variant="outline" className="w-full mt-4">
              {t('admin.recentUsers.viewAll')}
            </Button>
          </CardContent>
        </Card>
      </motion.div>

      {/* Activity Chart Placeholder */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.6, duration: 0.5 }}
      >
        <Card className="card-minimal">
        <CardHeader>
          <CardTitle className="text-lg font-semibold">{t('admin.activity.title')}</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="h-64 flex items-center justify-center bg-gray-50 rounded-lg">
            <div className="text-center">
              <TrendingUp className="w-12 h-12 text-gray-400 mx-auto mb-2" />
              <p className="text-gray-500">{t('admin.activity.chartComingSoon')}</p>
              <p className="text-sm text-gray-400 mt-1">{t('admin.activity.chartPending')}</p>
            </div>
          </div>
        </CardContent>
      </Card>
      </motion.div>
    </motion.div>
  );
}
